version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29-alpha

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Test project
          command: ./gradlew test