# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Assemble Build"
  lane :assemble_build do |options|
  gradle(
  task: "assemble",
  flavor: options[:dev],
  build_type: options[:debug]
  )
  end

  desc "Run Unit Test"
  lane :run_unit_test do |options|
  gradle(
  task:"test",
  flavor: options[:dev],
  build_type: options[:debug]
  )
  end

end
